fastq_dir: "samples"
genome_dir: "/scratch/slrinzema/dna_methylation/test/hg38"
results: "results"
samplesheet: "samples.tsv"


# I think spikein_1 is unmethylated
spikein_1: "/scratch/slrinzema/dna_methylation/test/Lambda_NEB"
spikein_2: "/scratch/slrinzema/dna_methylation/test/pUC19_vector"